import Foundation

/// Tunables for ``SummarizationMiddleware`` — Mispher's port of the knobs on LangChain/deepagents'
/// `SummarizationMiddleware`. ``default`` matches deepagents: trigger at 85% of the model's context
/// window, keep the most recent turns, and fall back to a 32k window for models that don't report one.
public struct SummarizationConfig: Sendable {
    /// Fraction of the model's context window at which automatic compaction fires (deepagents: 0.85).
    public var triggerFraction: Double
    /// Context window assumed when the model doesn't report ``ChatModel/contextWindowTokens``.
    public var fallbackContextWindow: Int
    /// How many of the most recent messages to keep verbatim - the upper bound on the tail. The cut is
    /// then snapped to a user-turn boundary so a kept tail never starts on an orphan tool result (see
    /// deepagents' "keep 6"). ``keepRecentFraction`` can tighten this further when the recent messages
    /// are large.
    public var keepRecentMessages: Int
    /// Token ceiling on the kept tail, as a fraction of the model's context window. The tail keeps the
    /// most recent messages up to ``keepRecentMessages`` *and* within this many tokens, whichever is
    /// fewer - so a handful of large recent messages (e.g. big tool results) can't leave the tail
    /// oversized. Keeping it well under ``triggerFraction`` guarantees the post-compaction history has
    /// real headroom before the next trigger.
    public var keepRecentFraction: Double
    /// Tokens reserved for the summary's own generation, kept clear when sizing the summarizer input
    /// so the summarization call itself cannot overflow the window.
    public var reservedOutputTokens: Int
    /// The instruction prepended to the rendered older conversation when asking the model to summarize.
    public var summaryPrompt: String

    public init(
        triggerFraction: Double = 0.85,
        fallbackContextWindow: Int = 32768,
        keepRecentMessages: Int = 6,
        keepRecentFraction: Double = 0.25,
        reservedOutputTokens: Int = 4096,
        summaryPrompt: String = SummarizationMiddleware.defaultSummaryPrompt
    ) {
        self.triggerFraction = triggerFraction
        self.fallbackContextWindow = fallbackContextWindow
        self.keepRecentMessages = keepRecentMessages
        self.keepRecentFraction = keepRecentFraction
        self.reservedOutputTokens = reservedOutputTokens
        self.summaryPrompt = summaryPrompt
    }

    public static let `default` = SummarizationConfig()
}

/// The result of one compaction — surfaced as a ``CompactionOutcome``-bearing ``AgentEvent`` for the
/// automatic path and returned directly from ``ReactAgent/compact(threadId:)`` for the manual one.
public struct CompactionOutcome: Sendable {
    /// Estimated tokens in the history before compaction.
    public let tokensBefore: Int
    /// Estimated tokens in the rewritten `[summary] + tail` history.
    public let tokensAfter: Int
    /// Where the evicted originals were saved, if an archive was wired and writing succeeded.
    public let archivePath: String?
    /// The rewritten history, so a host can refresh its transcript without re-reading from disk.
    public let messages: [AgentMessage]

    public init(tokensBefore: Int, tokensAfter: Int, archivePath: String?, messages: [AgentMessage]) {
        self.tokensBefore = tokensBefore
        self.tokensAfter = tokensAfter
        self.archivePath = archivePath
        self.messages = messages
    }
}

/// Summarization / context compaction — Mispher's port of LangChain & deepagents'
/// `SummarizationMiddleware`. Before each model call it measures the running history and, once it
/// reaches ``SummarizationConfig/triggerFraction`` of the model's context window, replaces the older
/// block with a single **summary turn** generated by **the same model**, keeping the recent tail
/// verbatim. The agent's history therefore *becomes* `[summary] + [recent tail]`; a later compaction
/// folds the prior summary plus the next block into a fresh summary, so it stays compact indefinitely
/// (the rolling model).
///
/// The summary is inserted as a `.human` turn marked ``AgentMessage/summarizationSource`` (matching
/// LangChain, which uses a `HumanMessage` with `lc_source` — a second `system` message mid-history is
/// rejected by some providers and breaks the LFM chat template), followed by a short `.ai`
/// acknowledgment so the seam alternates roles for every backend. The evicted originals are offloaded
/// via ``CompactionArchive`` first, and that path is embedded in the summary so nothing is lost.
public struct SummarizationMiddleware: AgentMiddleware {
    let model: any ChatModel
    let archive: (any CompactionArchive)?
    let tokenCounter: any TokenCounter
    let config: SummarizationConfig

    public var name: String { "summarization" }

    public init(
        model: any ChatModel,
        archive: (any CompactionArchive)? = nil,
        tokenCounter: any TokenCounter = ApproximateTokenCounter(),
        config: SummarizationConfig = .default
    ) {
        self.model = model
        self.archive = archive
        self.tokenCounter = tokenCounter
        self.config = config
    }

    public func beforeModel(_ state: inout AgentState) async {
        let threadId = state.values[Self.threadIdStateKey] as? String
        let overheadText = state.values[Self.promptOverheadStateKey] as? String ?? ""
        let overhead = overheadText.isEmpty ? 0 : tokenCounter.count(overheadText)
        if let outcome = await compact(
            &state.messages, threadId: threadId, force: false, overheadTokens: overhead
        ) {
            state.values[Self.outcomeStateKey] = outcome
        }
    }

    /// Compact `messages` in place. Automatic callers pass `force: false` (a no-op below the trigger);
    /// the manual `/compact` passes `force: true` to compact regardless of the current size.
    /// `overheadTokens` is the fixed per-turn prompt cost the conversation rides alongside (the system
    /// prompt and tool schemas) so the trigger measures the real request size, not just the messages.
    /// Returns the outcome when it rewrote the history, or `nil` when nothing was done (under threshold
    /// and not forced, no safe cut point, the summarizer produced nothing, or the rewrite wouldn't
    /// shrink the conversation).
    @discardableResult
    public func compact(
        _ messages: inout [AgentMessage], threadId: String?, force: Bool, overheadTokens: Int = 0
    ) async -> CompactionOutcome? {
        let window = model.contextWindowTokens ?? config.fallbackContextWindow
        let threshold = Int(Double(window) * config.triggerFraction)
        let messageTokensBefore = tokenCounter.count(messages)
        let before = messageTokensBefore + overheadTokens
        guard force || before >= threshold else { return nil }

        // Bound the kept tail by both message count and tokens (a fraction of the window), so a few
        // large recent messages can't leave it oversized; then snap to a user-turn boundary.
        let keepTokens = max(1, Int(Double(window) * config.keepRecentFraction))
        guard let cut = Self.cutIndex(
            messages, keepRecentMessages: config.keepRecentMessages,
            keepRecentTokens: keepTokens, counter: tokenCounter
        ) else { return nil }
        let evicted = Array(messages[..<cut])
        let tail = Array(messages[cut...])
        guard !evicted.isEmpty, !tail.isEmpty else { return nil }

        let rendered = Self.render(evicted)
        guard !rendered.isEmpty else { return nil }
        let budgetChars = max(1024, window - config.reservedOutputTokens) * 4
        let clamped = Self.clampToBudget(rendered, maxChars: budgetChars)

        guard let summary = await summarize(clamped), !summary.isEmpty else { return nil }

        // Bail before touching disk if the rewrite wouldn't shrink the conversation: a summary no
        // smaller than what it replaces is pointless, and on the automatic path it would re-fire every
        // round (a thrash). The fixed overhead is constant across the rewrite, so the guard compares
        // message tokens only.
        let provisional = [Self.summaryMessage(summary, archivePath: nil), Self.acknowledgmentMessage()] + tail
        guard tokenCounter.count(provisional) < messageTokensBefore else { return nil }

        // Only now that we have a usable, shrinking summary do we offload the evicted originals — so a
        // failed/empty/no-shrink compaction never leaves an orphan `history/part-N.jsonl` behind. A
        // prior summary turn in `evicted` was already archived in an earlier part (and the synthetic
        // ack isn't worth keeping), so offload only the true originals.
        let originals = evicted.filter { !$0.isSummary }
        var archivePath: String?
        if let archive, let threadId, !originals.isEmpty {
            archivePath = await archive.archive(originals, threadId: threadId)
        }

        messages = [Self.summaryMessage(summary, archivePath: archivePath), Self.acknowledgmentMessage()] + tail
        return CompactionOutcome(
            tokensBefore: before,
            tokensAfter: tokenCounter.count(messages) + overheadTokens,
            archivePath: archivePath,
            messages: messages
        )
    }

    // MARK: - Summarization call

    /// Run one summary generation on the same model. Failures are swallowed (returns `nil`) so an
    /// automatic compaction can never break a run; the round then proceeds on the un-compacted history.
    private func summarize(_ conversation: String) async -> String? {
        let prompt = config.summaryPrompt + "\n\nConversation to summarize:\n\n" + conversation
        do {
            let session = model.makeSession()
            let message = try await session.nextTurn(
                messages: [.human(prompt)], systemPrompt: nil, tools: [], onChunk: { _ in }
            )
            return message.text.trimmingCharacters(in: .whitespacesAndNewlines)
        } catch {
            return nil
        }
    }

    // MARK: - Message construction

    private static func summaryMessage(_ summary: String, archivePath: String?) -> AgentMessage {
        // Point at the directory the part lives in, not the single part file: rolling compactions write
        // part-1, part-2, … into the same folder, so referencing the folder keeps every earlier part
        // discoverable from the current summary (a lone part-N pointer would lose parts 1…N-1).
        let pointer = archivePath.map { path -> String in
            let directory = (path as NSString).deletingLastPathComponent
            let location = directory.isEmpty ? path : directory
            return " The full earlier transcript is preserved under \(location) "
                + "(one part file per compaction) if you need to refer back to it."
        } ?? ""
        let content = "You are continuing a conversation whose earlier messages have been summarized."
            + pointer + " A condensed summary of what happened so far follows:\n\n" + summary
        var message = AgentMessage.human(content)
        message.source = AgentMessage.summarizationSource
        return message
    }

    private static func acknowledgmentMessage() -> AgentMessage {
        var message = AgentMessage.ai("Understood. I'll continue from the summary above.")
        message.source = AgentMessage.summarizationSource
        return message
    }

    // MARK: - Cut selection

    /// Count-only cut: keep the last `keepRecent` messages, then snap to a user-turn boundary. The
    /// token-aware ``cutIndex(_:keepRecentMessages:keepRecentTokens:counter:)`` is what `compact`
    /// actually uses; this thin wrapper remains for callers that only care about the message count.
    static func safeCutIndex(_ messages: [AgentMessage], keepRecent: Int) -> Int? {
        guard messages.count > max(1, keepRecent) else { return nil }
        return snapToHumanBoundary(messages, target: messages.count - keepRecent)
    }

    /// The index the kept tail starts at, or `nil` when there is nothing safe to summarize. The raw
    /// target keeps the most recent messages bounded by BOTH `keepRecentMessages` and `keepRecentTokens`
    /// (whichever keeps fewer), so a few large recent messages can't leave the tail oversized. That
    /// target is then snapped to a user-turn (`.human`) boundary (see ``snapToHumanBoundary(_:target:)``).
    static func cutIndex(
        _ messages: [AgentMessage], keepRecentMessages: Int, keepRecentTokens: Int, counter: any TokenCounter
    ) -> Int? {
        guard messages.count > max(1, keepRecentMessages) else { return nil }
        let countTarget = messages.count - keepRecentMessages
        let tokenTarget = tailTokenTarget(messages, maxTokens: keepRecentTokens, counter: counter)
        return snapToHumanBoundary(messages, target: max(countTarget, tokenTarget))
    }

    /// The lowest index whose suffix `messages[index...]` still fits within `maxTokens`, walking back
    /// from the end. At least the final message is always kept (even if it alone exceeds the budget),
    /// so the tail never collapses to nothing.
    private static func tailTokenTarget(
        _ messages: [AgentMessage], maxTokens: Int, counter: any TokenCounter
    ) -> Int {
        var total = 0
        var index = messages.count
        while index > 0 {
            let cost = counter.count(tokenizableText(of: messages[index - 1]))
            if total + cost > maxTokens, total > 0 { break } // keep at least the last message
            total += cost
            index -= 1
        }
        return index
    }

    /// Snap a raw cut `target` to a user-turn (`.human`) boundary — preferring the next one at/after
    /// the target (summarize a little more), else the previous one — so the kept tail never begins on
    /// an orphan `.tool` result and no `.ai`+`.tool` group is split. Returns `nil` when the only
    /// boundary is the very start (nothing to evict).
    private static func snapToHumanBoundary(_ messages: [AgentMessage], target: Int) -> Int? {
        let target = min(max(target, 0), messages.count)
        if let forward = messages[target...].firstIndex(where: { $0.role == .human }), forward > 0 {
            return forward
        }
        if let backward = messages[..<target].lastIndex(where: { $0.role == .human }), backward > 0 {
            return backward
        }
        return nil
    }

    // MARK: - Rendering

    /// Render the older messages as plain text for the summarizer. A prior summary turn is included as
    /// "Earlier summary" so the new summary subsumes it; the synthetic ack is skipped.
    static func render(_ messages: [AgentMessage]) -> String {
        messages.compactMap { message -> String? in
            if message.isSummary, message.role == .ai { return nil } // skip the synthetic ack
            let who: String = switch message.role {
            case .system: "System"
            case .human: message.isSummary ? "Earlier summary" : "User"
            case .ai: "Assistant"
            case .tool: "Tool result"
            }
            var line = "\(who): \(message.text)"
            if !message.toolCalls.isEmpty {
                let calls = message.toolCalls
                    .map { "\($0.name)(\($0.describedArguments))" }
                    .joined(separator: "; ")
                line += "\nCalled: \(calls)"
            }
            return line
        }
        .joined(separator: "\n\n")
    }

    /// Keep the summarizer input within `maxChars` by dropping the middle (both the early intent and
    /// the most recent pre-cut context survive), noting the elision so the model knows it saw a gap.
    /// The elision marker's length is subtracted from the head/tail budget, so the result is a hard
    /// cap: `result.count <= maxChars` whenever clamping applies.
    static func clampToBudget(_ text: String, maxChars: Int) -> String {
        let marker = "\n\n[... middle of the earlier conversation omitted to fit the summarizer ...]\n\n"
        guard text.count > maxChars, maxChars > marker.count + 200 else { return text }
        let budget = maxChars - marker.count
        let headLen = budget / 2
        let tailLen = budget - headLen
        return String(text.prefix(headLen)) + marker + String(text.suffix(tailLen))
    }

    // MARK: - State keys

    /// `state.values` key the loop seeds with the run's thread id, so this middleware can address the
    /// archive without the hook signatures carrying it.
    public static let threadIdStateKey = "__compaction.threadId"
    /// `state.values` key this middleware sets with the ``CompactionOutcome`` so ``ReactAgent`` can
    /// emit a ``AgentEvent/contextCompacted(tokensBefore:tokensAfter:)`` for the UI.
    public static let outcomeStateKey = "__compaction.outcome"
    /// `state.values` key the loop seeds with the fixed prompt overhead text (system prompt + tool
    /// schemas) so the trigger can count it alongside the conversation - the model sees it every turn,
    /// so a long system prompt or many tools must count toward the 85%.
    public static let promptOverheadStateKey = "__compaction.promptOverhead"

    /// A plain-text rendering of the fixed prompt overhead the model sees every turn: the system prompt
    /// plus each tool's name, description, and parameter names/descriptions. Approximate (matching the
    /// char-based counter) - the exact serialized bytes depend on the backend codec, but this tracks
    /// the dominant cost (long system prompts, many tools) so the 85% trigger isn't blind to it.
    public static func promptOverheadText(systemPrompt: String?, tools: [any AgentTool]) -> String {
        var parts: [String] = []
        if let systemPrompt, !systemPrompt.isEmpty { parts.append(systemPrompt) }
        for tool in tools {
            var schema = tool.name + " " + tool.description
            for parameter in tool.parameters { schema += " " + parameter.name + " " + parameter.description }
            parts.append(schema)
        }
        return parts.joined(separator: "\n")
    }

    /// The default instruction asking the model to preserve everything that matters for continuing.
    public static let defaultSummaryPrompt = """
    You are compacting a long agent conversation to fit the context window. Write a thorough but \
    concise summary of the conversation below so the agent can keep working with no loss of important \
    context. Preserve:
    - The user's goals, intent, and any explicit instructions or constraints.
    - Key decisions made and the reasoning behind them.
    - Files, artifacts, or outputs created or modified (with their paths or identifiers).
    - Important facts, findings, and results learned from tool calls.
    - The current state of the work and what remains to be done next.
    Write in plain prose or bullet points. Do not invent details that are not present. Output only the \
    summary, with no preamble.
    """
}
